project_id = "ybqxpngkbgosobtetxac"

[functions.send-quote-email]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.cleanup-deleted-items]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.sync-google-ads]
verify_jwt = false